# Agent Platform Default Configuration (YAML Format)
# This file imports the properties file to maintain single source of truth

spring:
  config:
    import:
      - classpath:agent-platform.properties

# Optional: YAML-specific overrides can be added here if needed
# embabel:
#   agent:
#     platform:
#       # Any YAML-specific customizations would go here
#       # But generally, keep everything in agent-platform.properties