# This workflow will build a Java / Kotlin project with Maven

name: Deploy Snapshots

on:
  workflow_dispatch:  # Enables manual triggering

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Configure Maven Settings
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: ${{secrets.EMBABEL_ARTIFACTORY}}
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        
        run: mvn -U -DskipTests=true deploy
